#!/bin/bash

# .ycm_extra_conf.py
curl -fLo ~/.ycm_extra_conf.py \
    https://raw.githubusercontent.com/HmyBmny/vimrc/master/ycm_extra_conf.py

# plug.vim
curl --insecure -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# .vimrc
curl -fLo ~/.vimrc \
    https://raw.githubusercontent.com/HmyBmny/vimrc/master/vimrc

vim +PlugInstall
